-- DWHDATA.PN_GRUPOS_PAIS_DIM definition

CREATE TABLE "DWHDATA"."PN_GRUPOS_PAIS_DIM" 
   (	"ID_GRUPO_PAIS" NUMBER(5,0) NOT NULL ENABLE, 
	"NOM_GRUPO_PAIS" VARCHAR2(50) NOT NULL ENABLE, 
	"NOM_MONEDA" VARCHAR2(50), 
	 CONSTRAINT "PN_GRUPOS_PAIS_PK" PRIMARY KEY ("ID_GRUPO_PAIS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DWHDAT"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DWHDAT"   NO INMEMORY ;

CREATE UNIQUE INDEX "DWHDATA"."PN_GRUPOS_PAIS_PK" ON "DWHDATA"."PN_GRUPOS_PAIS_DIM" ("ID_GRUPO_PAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DWHDAT" ;

GRANT DELETE ON "DWHDATA"."PN_GRUPOS_PAIS_DIM" TO "DWHAPL";
  GRANT INSERT ON "DWHDATA"."PN_GRUPOS_PAIS_DIM" TO "DWHAPL";
  GRANT SELECT ON "DWHDATA"."PN_GRUPOS_PAIS_DIM" TO "DWHAPL";
  GRANT UPDATE ON "DWHDATA"."PN_GRUPOS_PAIS_DIM" TO "DWHAPL";
  GRANT SELECT ON "DWHDATA"."PN_GRUPOS_PAIS_DIM" TO "DWHQRY";
  GRANT SELECT ON "DWHDATA"."PN_GRUPOS_PAIS_DIM" TO "MICROST";
  GRANT SELECT ON "DWHDATA"."PN_GRUPOS_PAIS_DIM" TO "MICROST_SVC";
  GRANT SELECT ON "DWHDATA"."PN_GRUPOS_PAIS_DIM" TO "MICROST_IND";
  GRANT SELECT ON "DWHDATA"."PN_GRUPOS_PAIS_DIM" TO "MICROST_ECS";
  GRANT SELECT ON "DWHDATA"."PN_GRUPOS_PAIS_DIM" TO "DWHCDC";
  GRANT SELECT ON "DWHDATA"."PN_GRUPOS_PAIS_DIM" TO "DWHALM";
  GRANT SELECT ON "DWHDATA"."PN_GRUPOS_PAIS_DIM" TO "DWHBI";

COMMENT ON COLUMN DWHDATA.PN_GRUPOS_PAIS_DIM.ID_GRUPO_PAIS IS 'IDENTIFICAOR';